name: XMake Build

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger the workflow on pull requests targeting the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # You can choose other OS runners like windows-latest or macos-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Checkout the repository

      - name: Install xmake
        run: |
          sudo apt update
          sudo apt install -y build-essential
          wget https://github.com/xmake-io/xmake/releases/download/v2.8.5/xmake-linux-x64-v2.8.5.tar.gz
          tar -xvf xmake-linux-x64-v2.8.5.tar.gz
          sudo mv xmake /usr/local/bin

      - name: Build with xmake
        run: |
          xmake f -c  # Clean previous builds
          xmake       # Build the project

      - name: Run tests (optional)
        run: |
          xmake run tests  # Replace with your own test command
